package tencentcloud

const (
	DCDB_STATUS_UNOPEN  = 0
	DCDB_STATUS_OPENED  = 1
	DCDB_STATUS_CLOSED  = 2
	DCDB_STATUS_OPENING = 3
)

const (
	DCDB_DCN_FLAG_MASTER = 1
	DCDB_DCN_FLAG_SLAVE  = 2
)

const (
	DCDB_LOWER_CASE_TABLE_NAMES_0 = 0
	DCDB_LOWER_CASE_TABLE_NAMES_1 = 1
)

const (
	DCDB_CHARACTER_SET_UTF8    = "utf8"
	DCDB_CHARACTER_SET_GBK     = "gbk"
	DCDB_CHARACTER_SET_LATIN1  = "latin1"
	DCDB_CHARACTER_SET_UTF8MB4 = "utf8mb4"
	DCDB_CHARACTER_SET_GB18030 = "gb18030"
)

var DCDB_CHARACTER_SET = []string{
	DCDB_CHARACTER_SET_UTF8,
	DCDB_CHARACTER_SET_GBK,
	DCDB_CHARACTER_SET_LATIN1,
	DCDB_CHARACTER_SET_UTF8MB4,
	DCDB_CHARACTER_SET_GB18030,
}

var DCDB_LOWER_CASE_TABLE_NAMES = []int{
	DCDB_LOWER_CASE_TABLE_NAMES_0,
	DCDB_LOWER_CASE_TABLE_NAMES_1,
}
