package tencentcloud

const (
	TURBOFS_PROTCOL = "TURBO"

	TURBOFS_STORAGE_TYPE_TP = "TP"
	TURBOFS_STORAGE_TYPE_TB = "TB"

	TURBOFS_NETINTERFACE_VPC   = "VPC"
	TURBOFS_NETINTERFACE_BASIC = "BASIC"

	TURBOFS_CFS_VERSION = "4.0"

	TURBOFS_SNAPSHOT_POLICY_DAY   = "interval_days"
	TURBOFS_SNAPSHOT_POLICY_WEEK  = "day_of_week"
	TURBOFS_SNAPSHOT_POLICY_MONTH = "day_of_month"

	TURBOFS_RW_PERMISSION_RO = "RO"
	TURBOFS_RW_PERMISSION_RW = "RW"

	TURBOFS_USER_PERMISSION_ALL_SQUASH     = "all_squash"
	TURBOFS_USER_PERMISSION_NO_ALL_SQUASH  = "no_all_squash"
	TURBOFS_USER_PERMISSION_ROOT_SQUASH    = "root_squash"
	TURBOFS_USER_PERMISSION_NO_ROOT_SQUASH = "no_root_squash"

	TURBOFS_LIFECYCLE_STATE_AVAILABLE = "available"
	TURBOFS_LIFECYCLE_STATE_CREATING  = "creating"
	TURBOFS_LIFECYCLE_STATE_EXPANDING = "expanding"
	TURBOFS_LIFECYCLE_STATE_ABNORMAL  = "abnormal"
)

var TURBOFS_STORAGE_TYPE = []string{
	TURBOFS_STORAGE_TYPE_TP,
	TURBOFS_STORAGE_TYPE_TB,
}

var TURBOFS_NETINTERFACE = []string{
	TURBOFS_NETINTERFACE_VPC,
	TURBOFS_NETINTERFACE_BASIC,
}

var TURBOFS_SNAPSHOT_POLICY_CYCLE = []string{
	TURBOFS_SNAPSHOT_POLICY_DAY,
	TURBOFS_SNAPSHOT_POLICY_WEEK,
	TURBOFS_SNAPSHOT_POLICY_MONTH,
}

var TURBOFS_RW_PERMISSION = []string{
	TURBOFS_RW_PERMISSION_RO,
	TURBOFS_RW_PERMISSION_RW,
}

var TURBOFS_USER_PERMISSION = []string{
	TURBOFS_USER_PERMISSION_ALL_SQUASH,
	TURBOFS_USER_PERMISSION_NO_ALL_SQUASH,
	TURBOFS_USER_PERMISSION_ROOT_SQUASH,
	TURBOFS_USER_PERMISSION_NO_ROOT_SQUASH,
}
