package tencentcloud

const (
	BMS_CHARGE_TYPE_PREPAID  = "PREPAID"
	BMS_CHARGE_TYPE_POSTPAID = "POSTPAID_BY_HOUR"
	BMS_CHARGE_TYPE_SPOTPAID = "SPOTPAID"
	BMS_CHARGE_TYPE_CDHPAID  = "CDHPAID"

	BMS_INTERNET_CHARGE_TYPE_BANDWIDTH_PREPAID  = "BANDWIDTH_PREPAID"
	BMS_INTERNET_CHARGE_TYPE_BANDWIDTH_POSTPAID = "BANDWIDTH_POSTPAID_BY_HOUR"
	BMS_INTERNET_CHARGE_TYPE_BANDWIDTH_PACKAGE  = "BANDWIDTH_PACKAGE"
	BMS_INTERNET_CHARGE_TYPE_TRAFFIC_POSTPAID   = "TRAFFIC_POSTPAID_BY_HOUR"

	BMS_STATUS_RUNNING       = "RUNNING"
	BMS_STATUS_STOPPED       = "STOPPED"
	BMS_STATUS_SHUTDOWN      = "SHUTDOWN"
	BMS_STATUS_TERMINATING   = "TERMINATING"
	BMS_STATUS_CREATE_FAILED = "CREATE_FAILED"
	BMS_STATUS_LAUNCH_FAILED = "LAUNCH_FAILED"

	BMS_LATEST_OPERATION_STATE_OPERATING = "OPERATING"
	BMS_LATEST_OPERATION_STATE_SUCCESS   = "SUCCESS"
	BMS_LATEST_OPERATION_STATE_FAILED    = "FAILED"

	BMS_PREPAID_RENEW_FLAG_NOTIFY_NOTIFY_AND_AUTO_RENEW    = "NOTIFY_AND_AUTO_RENEW"
	BMS_PREPAID_RENEW_FLAG_NOTIFY_AND_MANUAL_RENEW         = "NOTIFY_AND_MANUAL_RENEW"
	BMS_PREPAID_RENEW_FLAG_DISABLE_NOTIFY_AND_MANUAL_RENEW = "DISABLE_NOTIFY_AND_MANUAL_RENEW"

	BMS_DISK_TYPE_LOCAL_BASIC   = "LOCAL_BASIC"
	BMS_DISK_TYPE_LOCAL_SSD     = "LOCAL_SSD"
	BMS_DISK_TYPE_CLOUD_BASIC   = "CLOUD_BASIC"
	BMS_DISK_TYPE_CLOUD_SSD     = "CLOUD_SSD"
	BMS_DISK_TYPE_CLOUD_PREMIUM = "CLOUD_PREMIUM"
	BMS_DISK_TYPE_CLOUD_BSSD    = "CLOUD_BSSD"
	BMS_DISK_TYPE_CLOUD_HSSD    = "CLOUD_HSSD"

	BMS_PLACEMENT_GROUP_TYPE_HOST = "HOST"
	BMS_PLACEMENT_GROUP_TYPE_SW   = "RACK_SAME_SW"
	BMS_PLACEMENT_GROUP_TYPE_RACK = "RACK"

	BMS_NOT_FOUND_ERROR = "InvalidInstanceId.NotFound"

	BMS_SPOT_INSTANCE_TYPE_ONE_TIME = "ONE-TIME"

	BMS_MARKET_TYPE_SPOT = "spot"

	BMS_IMAGE_LOGIN     = "TRUE"
	BMS_IMAGE_LOGIN_NOT = "FALSE"

	// @Deprecated use BMS.INVALIDPARAMETERVALUE_ZONENOTSUPPORTED
	BMS_ZONE_NOT_SUPPORT_ERROR = "InvalidParameterValue.ZoneNotSupported"
	// @Deprecated use BMS.RESOURCEINSUFFICIENT_CLOUDDISKSOLDOUT instead
	BMS_CLOUD_DISK_SOLD_OUT_ERROR = "ResourceInsufficient.CloudDiskSoldOut"

	BMS_STOP_MODE_KEEP_CHARGING = "KEEP_CHARGING"
	BMS_STOP_MODE_STOP_CHARGING = "STOP_CHARGING"
	BMS_SELL_STATUS             = "SELL"
	BMS_SOLD_OUT_STATUS         = "SOLD_OUT"

	BMS_PLACE_GROUP_STRATEGY_SPREAD          = "SPREAD"
	BMS_PLACE_GROUP_STRATEGY_FORCED_AFFINITY = "FORCED_AFFINITY"
)

// Only client error can BMS retry, others will directly returns
var BMS_RETRYABLE_ERROR = []string{
	// client
	//"ClientError.NetworkError",
	"ClientError.HttpStatusCodeError",
}

var BMS_CHARGE_TYPE = []string{
	BMS_CHARGE_TYPE_PREPAID,
	BMS_CHARGE_TYPE_POSTPAID,
	BMS_CHARGE_TYPE_SPOTPAID,
	BMS_CHARGE_TYPE_CDHPAID,
}

var BMS_INTERNET_CHARGE_TYPE = []string{
	BMS_INTERNET_CHARGE_TYPE_BANDWIDTH_PREPAID,
	BMS_INTERNET_CHARGE_TYPE_BANDWIDTH_POSTPAID,
	BMS_INTERNET_CHARGE_TYPE_BANDWIDTH_PACKAGE,
	BMS_INTERNET_CHARGE_TYPE_TRAFFIC_POSTPAID,
}

var BMS_PREPAID_PERIOD = []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 24, 36}

var BMS_PREPAID_RENEW_FLAG = []string{
	BMS_PREPAID_RENEW_FLAG_NOTIFY_NOTIFY_AND_AUTO_RENEW,
	BMS_PREPAID_RENEW_FLAG_NOTIFY_AND_MANUAL_RENEW,
	BMS_PREPAID_RENEW_FLAG_DISABLE_NOTIFY_AND_MANUAL_RENEW,
}

var BMS_DISK_TYPE = []string{
	BMS_DISK_TYPE_LOCAL_BASIC,
	BMS_DISK_TYPE_LOCAL_SSD,
	BMS_DISK_TYPE_CLOUD_BASIC,
	BMS_DISK_TYPE_CLOUD_SSD,
	BMS_DISK_TYPE_CLOUD_PREMIUM,
	BMS_DISK_TYPE_CLOUD_BSSD,
}

var BMS_PLACEMENT_GROUP_TYPE = []string{
	//BMS_PLACEMENT_GROUP_TYPE_HOST,
	BMS_PLACEMENT_GROUP_TYPE_SW,
	BMS_PLACEMENT_GROUP_TYPE_RACK,
}

var BMS_SPOT_INSTANCE_TYPE = []string{
	BMS_SPOT_INSTANCE_TYPE_ONE_TIME,
}

var BMS_PLACE_GROUP_STRATEGY = []string{
	BMS_PLACE_GROUP_STRATEGY_SPREAD,
	BMS_PLACE_GROUP_STRATEGY_FORCED_AFFINITY,
}
