package tencentcloud

const (
	TBASE_CHARACTER_SET_LATIN1    = "LATIN1"
	TBASE_CHARACTER_SET_SQL_ASCII = "SQL_ASCII"
	TBASE_CHARACTER_SET_UTF8      = "UTF8"
	TBASE_CHARACTER_SET_EUC_CN    = "EUC_CN"

	TBASE_DATABASE_USERNAME = "dbadmin"

	TBASE_PRODUCT = "tbase"
)

const (
	TBASE_ENGINE_TYPE_POSTGRESQL = "TbaseV2"
	TBASE_ENGINE_TYPE_ORACLE     = "TbaseV5"
	TBASE_ENGINE_TYPE_ORACEL_C   = "TbaseV5_C"
	TBASE_ENGINE_TYPE_ORACEL_H   = "TbaseH"
	TBASE_ENGINE_TYPE_ORACEL_HC  = "TbaseHC"
)

const (
	TBASE_PG_ENGINE_TYPE_POSTGRESQL          = "PostgreSQL"
	TBASE_PG_ENGINE_TYPE_POSTGRESQL_TBASE_XC = "TbaseXC"
)

var TBASE_CHARACTER_SET = []string{
	TBASE_CHARACTER_SET_UTF8,
	TBASE_CHARACTER_SET_LATIN1,
	TBASE_CHARACTER_SET_SQL_ASCII,
	TBASE_CHARACTER_SET_EUC_CN,
}

var TBASE_ENGINE_TYPE = []string{
	TBASE_ENGINE_TYPE_POSTGRESQL,
	TBASE_ENGINE_TYPE_ORACLE,
	TBASE_ENGINE_TYPE_ORACEL_C,
	TBASE_ENGINE_TYPE_ORACEL_H,
	TBASE_ENGINE_TYPE_ORACEL_HC,
}

var TBASE_PG_ENGINE_TYPE = []string{
	TBASE_PG_ENGINE_TYPE_POSTGRESQL,
	TBASE_PG_ENGINE_TYPE_POSTGRESQL_TBASE_XC,
}
